### ISSUE TITLE
Build Failure date format

### ISSUE THREAD

**Issue by hhh0505** [githublemming/CloudTrailViewer#11]
Im getting the following error when trying to package, any idea?

convertStringToDateTest(io.haskins.java.cloudtrailviewer.utils.DateFormatterTests)  Time elapsed: 0.013 sec  <<< FAILURE!
java.lang.AssertionError: expected:<Sun Jan 01 05:00:00 EST 2017> but was:<Sun Jan 01 10:00:00 EST 2017>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.haskins.java.cloudtrailviewer.utils.DateFormatterTests.convertStringToDateTest(DateFormatterTests.java:39)

**Comment by haskins-io** [comment]
Hi,

looks like it might be a timezone issue with the unit test. I'll have a look.

**Comment by hhh0505** [comment]
Works for now by removing the test in case someone else runs into it.

**Comment by haskins-io** [comment]
That unit test wasn't needed any more as it was testing code that was no longer being used so I've removed it
