### ISSUE TITLE
NoSuchMethodException in Event.getSrcCity()

### ISSUE THREAD

**Issue by JoshiiSinfield** [githublemming/CloudTrailViewer#14]
Hi,

Receiving the below when getting/parsing files from S3. These files are Lambda data events - not sure if that makes any difference?

N.B. the NPE only shows once at the end after loading all events.

Cheers,
Josh

2019-12-16 17:14:54.398  WARN 90582 --- [      Thread-13] CloudTrail                               : Problem using reflect to get property from object

java.lang.NoSuchMethodException: io.haskins.java.cloudtrailviewer.model.event.Event.getSrcCity()
	at java.lang.Class.getMethod(Class.java:1786) ~[na:1.8.0_231]
	at io.haskins.java.cloudtrailviewer.utils.EventUtils.callMethod(EventUtils.java:113) [cloudtrail-viewer.jar!/:3.1.0]
	at io.haskins.java.cloudtrailviewer.utils.EventUtils.getEventProperty(EventUtils.java:99) [cloudtrail-viewer.jar!/:3.1.0]
	at io.haskins.java.cloudtrailviewer.controller.widget.AbstractBaseController.addToKeyValueMap(AbstractBaseController.java:154) [cloudtrail-viewer.jar!/:3.1.0]
	at io.haskins.java.cloudtrailviewer.controller.widget.AbstractBaseController.newEvent(AbstractBaseController.java:216) [cloudtrail-viewer.jar!/:3.1.0]
	at io.haskins.java.cloudtrailviewer.service.EventService.processStream(EventService.java:262) [cloudtrail-viewer.jar!/:3.1.0]
	at io.haskins.java.cloudtrailviewer.service.EventService.access$300(EventService.java:57) [cloudtrail-viewer.jar!/:3.1.0]
	at io.haskins.java.cloudtrailviewer.service.EventService$1.call(EventService.java:111) [cloudtrail-viewer.jar!/:3.1.0]
	at io.haskins.java.cloudtrailviewer.service.EventService$1.call(EventService.java:87) [cloudtrail-viewer.jar!/:3.1.0]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) [jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_231]

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at io.haskins.java.cloudtrailviewer.controller.widget.MapWidgetController.finishedLoading(MapWidgetController.java:140)
	at io.haskins.java.cloudtrailviewer.service.EventService$1.succeeded(EventService.java:133)
	at javafx.concurrent.Task.setState(Task.java:724)
	at javafx.concurrent.Task$TaskCallable.lambda$call$1(Task.java:1434)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Comment by JoshiiSinfield** [comment]
If i add a new map widget I don't see the error.

It seems to be when the widgets already exist, empty, then load events that I get the reflection error.

I was using the default dashboard when the tool starts up.

**Comment by haskins-io** [comment]
Hi Josh,

I'm not able to replicate this. I have over 50,000 test events, and my map loads correctly. Though I will admit that I might not have any Lambda logs in there.

Let me see if I can generate from Lambda logs.

Mark

**Comment by haskins-io** [comment]
I think this might be something to do with the dashboard file that you are initially loading. It might be out of date. 

You should have a folder in your home directory called .cloudtrailviewer, inside there should be a file called default.ctd. If you delete or rename this and then restart the application another should appear.

Hopefully that will fix this problem. If you read this file first you might find that the seriesField value is SrcCity. when it should now be City.

Mark

**Comment by JoshiiSinfield** [comment]
Hi Mark,

I deleted the file and restarted it, everything works fine :)

Thanks for looking!

Cheers,
Josh
