### ISSUE TITLE
Logs from cross-account access not displayed

### ISSUE THREAD

**Issue by mludvig** [githublemming/CloudTrailViewer#2]
Hi we heavily use cross-account access in our environment but it looks like CloudTrail logs from these events are not displayed at all. For example when I open the attached file it doesn't display any events.
[cross-account.json.txt](https://github.com/githublemming/CloudTrailViewer/files/98487/cross-account.json.txt)

**Comment by haskins-io** [comment]
This is a bug relating to how the JSON files are currently being loaded. If one even fails to parse the whole file is ignored.

I have a solution for this and will hopefully get time to work on it in the next day or two.

**Comment by haskins-io** [comment]
Swapping out the JSON processing turned out to be less painful than I thought. I've delivered changes that work with your provided file.

The change can be pulled / clones or there is a new release with the fix. Let me know how you get on.

**Comment by mludvig** [comment]
Hi, I still keep getting this java error when loading logs from an account that's only accessed via cross-account AssumeRole credentials...

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at com.haskins.cloudtrailviewer.utils.TableUtils.getInvokedBy(TableUtils.java:64)
        at com.haskins.cloudtrailviewer.table.EventsTableModel.getValueAt(EventsTableModel.java:104)
        at javax.swing.JTable.getValueAt(JTable.java:2717)
        at javax.swing.JTable.prepareRenderer(JTable.java:5719)
        at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2108)
        at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2010)
        at javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1806)
        at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
        at javax.swing.JComponent.paintComponent(JComponent.java:770)
        at javax.swing.JComponent.paint(JComponent.java:1046)
        at javax.swing.JComponent.paintChildren(JComponent.java:879)
        at javax.swing.JComponent.paint(JComponent.java:1055)
        at javax.swing.JViewport.paint(JViewport.java:731)
        at javax.swing.JComponent.paintChildren(JComponent.java:879)
        at javax.swing.JComponent.paint(JComponent.java:1055)
        at javax.swing.JComponent.paintChildren(JComponent.java:879)
        at javax.swing.JSplitPane.paintChildren(JSplitPane.java:1047)
        at javax.swing.JComponent.paint(JComponent.java:1055)
        at javax.swing.JComponent.paintChildren(JComponent.java:879)
        at javax.swing.JComponent.paint(JComponent.java:1055)
        at javax.swing.JComponent.paintChildren(JComponent.java:879)
        at javax.swing.JComponent.paint(JComponent.java:1055)
        at javax.swing.JComponent.paintChildren(JComponent.java:879)
        at javax.swing.JComponent.paint(JComponent.java:1055)
        at javax.swing.JComponent.paintToOffscreen(JComponent.java:5223)
        at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:295)
        at javax.swing.RepaintManager.paint(RepaintManager.java:1249)
        at javax.swing.JComponent._paintImmediately(JComponent.java:5171)
        at javax.swing.JComponent.paintImmediately(JComponent.java:4982)
        at javax.swing.RepaintManager$3.run(RepaintManager.java:808)
        at javax.swing.RepaintManager$3.run(RepaintManager.java:796)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
        at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:796)
        at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:769)
        at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:718)
        at javax.swing.RepaintManager.access$1100(RepaintManager.java:62)
        at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1677)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:706)
        at java.awt.EventQueue$3.run(EventQueue.java:704)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by mludvig** [comment]
It's actually this file causing the crash... 
[crash.json.txt](https://github.com/githublemming/CloudTrailViewer/files/107542/crash.json.txt)

**Comment by mludvig** [comment]
And while we're at it - if the "User Identity" Arn is e.g. `arn:aws:sts::123456789012:assumed-role/cross-admin/test.user` it would be nice if the "Invoked By" column displayed the full `cross-admin/test.user` instead of just `cross-admin` as multiple users would typically assume the same role.

**Comment by haskins-io** [comment]
I've created a new release can you try that and see if it works for you.

The different ways that UserIdentity could be provided are not documented, so I've added a fallback that if something goes wrong it will just show the arn.

I've also changed the logic so when it's a 'Assumed' it shows the details of who did the assuming and not who issued the session. While I've tried my best to make the application as vanilla as possible I do occasionally implement the logic so it works best for the files I have to deal with, and this was one area where that was the case.

**Comment by haskins-io** [comment]
I've had to pull that release, I've moved over to a new development IDEA and it doesn't seem to be including all the files in the .jar file

**Comment by haskins-io** [comment]
This was fixed in the last release, I forgot to update the issue.
