### ISSUE TITLE
java.lang.NoClassDefFoundError: javafx/application/Application

### ISSUE THREAD

**Issue by mludvig** [githublemming/CloudTrailViewer#8]
Hi
I would love to use your CloudTrailViewer but since I'm not a Java developer I'm at stuck with this error and don't know how to move on:

```
~/tmp $ java -jar cloudtrail-viewer.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
	at java.lang.ClassLoader.defineClass1(java.base@9-internal/Native Method)
	at java.lang.ClassLoader.defineClass(java.base@9-internal/ClassLoader.java:939)
	at java.security.SecureClassLoader.defineClass(java.base@9-internal/SecureClassLoader.java:152)
	at java.net.URLClassLoader.defineClass(java.base@9-internal/URLClassLoader.java:463)
	at java.net.URLClassLoader.access$100(java.base@9-internal/URLClassLoader.java:76)
	at java.net.URLClassLoader$1.run(java.base@9-internal/URLClassLoader.java:371)
	at java.net.URLClassLoader$1.run(java.base@9-internal/URLClassLoader.java:365)
	at java.security.AccessController.doPrivileged(java.base@9-internal/Native Method)
	at java.net.URLClassLoader.findClass(java.base@9-internal/URLClassLoader.java:364)
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
	at java.lang.ClassLoader.loadClass(java.base@9-internal/ClassLoader.java:419)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at java.lang.Thread.run(java.base@9-internal/Thread.java:804)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.net.URLClassLoader.findClass(java.base@9-internal/URLClassLoader.java:384)
	at java.lang.ClassLoader.loadClass(java.base@9-internal/ClassLoader.java:486)
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:178)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
	at java.lang.ClassLoader.loadClass(java.base@9-internal/ClassLoader.java:419)
	... 14 more
```

My Java version is:

```
~ $ java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
```
I'm using Linux Mint 18.2 (based on Ubuntu Xenial). 

Would be nice to have an easy to use package that just works for us Java-noobs :)

**Comment by haskins-io** [comment]
Hi,

This error is caused by you not having JavaFX installed. JavaFX has been part of the Oracle Java distribution since Java 8, but I'm guessing it's not included by default by openJDK.

You will have to install it in order for the application to work. There is a section on the openjdk wiki about [openJFX](https://wiki.openjdk.java.net/display/OpenJFX/Main). Alternatively you could install the Oracle Java on your computer

**Comment by mludvig** [comment]
So much I figured out as well but couldn't find a way to install JavaFX on my laptop. Even tried to install Maven, Java SDK, and rebuild it but didn't get anywhere. 

For sure my fault as I didn't understand all the Java jargon and dependencies but given that your tool's target group are AWS admins and not Java devs you may want to provide a more fool proof package for users like me :)

BTW in the end managed to start it in Windows but there I couldn't get to the CloudTrail files - they were on Y:\ drive and I didn't find a way to switch drives in the file open dialog to open them...

Promising tool though, guessing from the screen shots.. ;)

**Comment by haskins-io** [comment]
The jar file is self contained and includes all required dependencies, but that does assume that it is being run using Oracle Java. I’ll update what little document I have to state this.

You don’t need to use the jar command to run the application. On most modern Operating Systems you can double click on the jar to run the application. Though I admit I need to update the documenation around this.

I don’t use windows myself so not being able to switch drives hadn’t been a problem. I will look at this and implement a solution.

Mark

**Comment by haskins-io** [comment]
* I've update the readme to make it clear that if you are not using Oracle Java then you will need to install the equivalent JavaFX library.
* I've also updated the readme to state that you can double click on the jar file to run the application and only use the Jar command as a fallback.
* I've updated the code so that when the application is running on windows you can navigate up the directory tree to the list of available drives. This code has been pushed back to GitHub but, will not form part of a release until probably this weekend when I have time.

**Comment by haskins-io** [comment]
I've done a beta release of a new version of the application which support Windows drives.

**Comment by mludvig** [comment]
Great, I can change drives in Windows now :) Thanks for looking at this so quickly!
